version: "3.8"

services:
  backend:
    build:
      context: ./courses-api
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./courses-ui
    ports:
      - "3000:80"
    depends_on:
      - backend
